django_start_project/urls.py
"""Platzigram URLs module."""

# Django
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('example_app/', include('example_app.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Users URLs."""

# Django
from django.urls import path

# View
from users import views


urlpatterns = [

    # Management
    path(
        route='login/',
        view=views.LoginView.as_view(),
        name='login'
    ),
    path(
        route='logout/',
        view=views.LogoutView.as_view(),
        name='logout'
    ),
    path(
        route='signup/',
        view=views.SignupView.as_view(),
        name='signup'
    ),
    path(
        route='me/profile/',
        view=views.UpdateProfileView.as_view(),
        name='update'
    )

]

users/models.py
"""Users models."""

# Django
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    """Profile model.

    Proxy model that extends the base data with other
    information.
    """

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(max_length=200, blank=True)
    biography = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20, blank=True)

    picture = models.ImageField(
        upload_to='users/pictures',
        blank=True,
        null=True
    )

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return username."""
        return self.user.username

users/forms.py
"""User forms."""

# Django
from django import forms

# Models
from django.contrib.auth.models import User
from users.models import Profile


class SignupForm(forms.Form):
    """Sign up form."""

    username = forms.CharField(min_length=4, max_length=50, label="Usuario")
    username.widget.attrs['class'] = 'form-control'
    username.widget.attrs['placeholder'] = 'Usuario'

    password = forms.CharField(max_length=70, widget=forms.PasswordInput(), label="Contraseña")
    password.widget.attrs['class'] = 'form-control'
    password.widget.attrs['placeholder'] = 'Contraseña'

    password_confirmation = forms.CharField(max_length=70, widget=forms.PasswordInput(), label="Confirmar contraseña")
    password_confirmation.widget.attrs['class'] = 'form-control'
    password_confirmation.widget.attrs['placeholder'] = 'Confirmar contraseña'

    first_name = forms.CharField(min_length=2, max_length=50, label="Nombres")
    first_name.widget.attrs['class'] = 'form-control'
    first_name.widget.attrs['placeholder'] = 'Nombres'

    last_name = forms.CharField(min_length=2, max_length=50, label="Apellidos")
    last_name.widget.attrs['class'] = 'form-control'
    last_name.widget.attrs['placeholder'] = 'Apellidos'

    email = forms.CharField(min_length=6, max_length=70, widget=forms.EmailInput(), label="Email")
    email.widget.attrs['class'] = 'form-control'
    email.widget.attrs['placeholder'] = 'Email'

    def clean_username(self):
        """Username must be unique."""
        username = self.cleaned_data['username']
        username_taken = User.objects.filter(username=username).exists()
        if username_taken:
            raise forms.ValidationError('El nombre de Usuario ya existe.')
        return username

    def clean(self):
        """Verify password confirmation match."""
        data = super().clean()

        password = data['password']
        password_confirmation = data['password_confirmation']

        if password != password_confirmation:
            raise forms.ValidationError('Las contraseñas no coinciden.')

        return data

    def save(self):
        """Create user and profile."""
        data = self.cleaned_data
        data.pop('password_confirmation')
        user = User.objects.create_user(**data)
        profile = Profile(user=user)
        profile.save()

users/views.py
# Django
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, FormView, UpdateView

# Models
from django.contrib.auth.models import User
from users.models import Profile

# Forms
from users.forms import SignupForm

class SignupView(FormView):
    """Users sign up view."""

    template_name = 'users/signup.html'
    form_class = SignupForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        """Save form data."""
        form.save()
        return super().form_valid(form)

class LoginView(auth_views.LoginView):
    """Login view."""

    template_name = 'users/login.html'


class LogoutView(LoginRequiredMixin, auth_views.LogoutView):
    """Logout view."""

    template_name = 'users/logged_out.html'

class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """Update profile view."""

    template_name = 'users/update_profile.html'
    model = Profile
    fields = ['website', 'biography', 'phone_number', 'picture']

    def get_object(self):
        """Return user's profile."""
        return self.request.user.profile

    def get_success_url(self):
        """Return to user's profile."""
        username = self.object.user.username
        return reverse('users:detail', kwargs={'username': username})

templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  {% block head_content %}{% endblock %}

  <!-- CSS -->
  <link href="{% static "vendor/fontawesome-free/css/all.css" %}" rel="stylesheet" type="text/css">
  <link href="{% static "css/font-family.css" %}" rel="stylesheet">
  <link href="{% static "css/sb-admin-2.css" %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">
  <!-- Login Container -->
  {% block container %}{% endblock%}
</body>

<!-- JavaScript-->
<script src="{% static "vendor/jquery/jquery.min.js" %}"></script>
<script src="{% static "vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<script src="{% static "vendor/jquery-easing/jquery.easing.min.js" %}"></script>
<script src="{% static "js/sb-admin-2.js" %}"></script>

</html>

templates/users/login.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
<title>Login</title>
{% endblock%}

{% block container %}

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center mt-5">

          <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                  <div class="col-lg-12">
                    {% if form.errors %}
                      <p class="alert alert-danger m-0" style="border-radius:0px;">
                        El usuario y/o la contraseña no coinciden. Por favor intente de Nuevo.
                      </p>
                    {% endif%}
                  </div>
                </div>
                <div class="row">
                  <div  class="col-lg-6 d-none d-lg-block"
                        style=" background: url({% static "img/login.jpg" %});
                                background-position: center;
                                background-size: cover;">
                  </div>
                  <div class="col-lg-6">
                    <div class="p-5">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Bienvenido!</h1>
                      </div>
                      <!-- Login Form -->
                      <form class="user" method="POST" action="{% url "users:login" %}">
                        {% csrf_token %}
                        <div class="form-group">
                          <input type="text" class="form-control form-control-user" id="username" name="username" placeholder="Usuario">
                        </div>
                        <div class="form-group">
                          <input type="password" class="form-control form-control-user" id="password" name="password" placeholder="Contraseña">
                        </div>
                        <button class="btn btn-primary btn-block btn-user mt-5" type="submit">Ingresar</button>
                      </form>
                      <hr>
                      <div class="text-center">
                        <a class="small" href="{% url "users:signup" %}">Registrate</a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>

          </div>

        </div>
    </div>



{% endblock %}

templates/users/signup.html
{% extends "users/base.html" %}

{% block head_content %}
<title>Registro</title>
{% endblock %}

{% block container %}

    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

          <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                  <div class="col-lg-12">
                    {% if form.errors %}
                      <div class="alert alert-danger m-0 p-0 pt-2" style="border-radius:0px;">
                        <ul>
                        {% for field, error in form.errors.items %}
                          <li>
                            {{ error|striptags }}
                          </li>
                        {% endfor %}
                        </ul>
                      </div>
                    {% endif %}
                  </div>
                </div>

                <div class="row">
                  <div class="col-lg-12">
                    <div class="px-5 py-3">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Registro</h1>
                      </div>
                      <!-- Signup Form -->
                      <form class="user" action="{% url 'users:signup' %}" method="POST">
                          {% csrf_token %}

                          {% for field in form %}
                            <div class="row">
                              <div class="form-group col-12">
                                <label style="font-weight: bold;">
                                  {{ field.label }}:
                                </label>
                                {{ field }}
                              </div>
                            </div>
                          {% endfor %}

                          <button class="btn btn-primary btn-block btn-user mt-3" type="submit">Enviar</button>
                      </form>
                      <hr>
                      <div class="text-center">
                        <a class="small" href="{% url "users:login" %}">Ingresar</a>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>

          </div>

        </div>
    </div>

{% endblock %}

templates/users/update_profile.html
{% extends "users/base.html" %}
{% load static %}

{% block head_content %}
<title>Actualizar</title>
{% endblock %}

{% block container %}

<div class="container">

    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">

          <div class="col-xl-10 col-lg-12 col-md-9">

            <div class="card o-hidden border-0 shadow-lg my-5">
              <div class="card-body p-0">
                <!-- Nested Row within Card Body -->
                <div class="row">
                  <div class="col-lg-12">
                    {% if form.errors %}
                      <div class="alert alert-danger m-0 p-0 pt-2" style="border-radius:0px;">
                        <ul>
                        {% for field, error in form.errors.items %}
                          <li>
                            {{ error|striptags }}
                          </li>
                        {% endfor %}
                        </ul>
                      </div>
                    {% endif %}
                  </div>
                </div>

                <div class="row">
                  <div class="col-lg-12">
                    <div class="px-5 py-3">
                      <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Actualizar Perfil</h1>
                      </div>
                      <!-- Form Update -->
                      <form action="{% url 'users:update' %}" method="POST" enctype="multipart/form-data">
                          {% csrf_token %}

                          <div class="media">
                              {% if profile.picture %}
                                  <img src="{{ profile.picture.url }}" class="rounded-circle" height="50" />
                              {% else%}
                                  <img src="{% static 'img/default-profile.png' %}" class="rounded-circle" height="50" />
                              {% endif %}

                              <div class="media-body">
                                  <h5 class="ml-4">@{{ user.username }} | {{ user.get_full_name }}</h5>
                                  <p class="ml-4"><input type="file" name="picture"></p>
                              </div>
                          </div>

                          {% for error in form.picture.errors %}
                          <div class="alert alert-danger">
                              <b>Picture: </b>{{ error }}
                          </div>
                          {% endfor %}

                          <hr><br>

                          {# Website field #}
                          <div class="form-group">
                              <label>Website</label>
                              <input
                                  class="form-control {% if form.website.errors %}is-invalid{% endif %}"
                                  type="text"
                                  name="website"
                                  placeholder="Website"
                                  value="{% if form.errors %}{{ form.website.value }}{% else %}{{ profile.website }}{% endif %}"
                              />
                              <div class="invalid-feedback">
                                  {% for error in form.website.errors %}
                                      {{ error }}
                                  {% endfor%}
                              </div>
                          </div>

                          {# Biography field #}
                          <div class="form-group">
                              <label>Biography</label>
                              <textarea
                                  class="form-control {% if form.biography.errors %}is-invalid{% endif %}"
                                  name="biography"
                              >{% if form.errors %}{{ form.biography.value }}{% else %}{{ profile.biography }}{% endif %}</textarea>

                              <div class="invalid-feedback">
                                  {% for error in form.biography.errors %}
                                      {{ error }}
                                  {% endfor%}
                              </div>
                          </div>

                          {# Phone number field #}
                          <div class="form-group">
                              <label>Phone number</label>
                              <input
                                  class="form-control {% if form.phone_number.errors %}is-invalid{% endif %}"
                                  type="text"
                                  name="phone_number"
                                  placeholder="Phone number"
                                  value="{% if form.errors %}{{ form.phone_number.value }}{% else %}{{ profile.phone_number }}{% endif %}"
                              />
                              <div class="invalid-feedback">
                                  {% for error in form.phone_number.errors %}
                                      {{ error }}
                                  {% endfor%}
                              </div>
                          </div>

                          <button type="submit" class="btn btn-primary btn-block mt-5">Update info</button>
                      </form>
                      <hr>
                      <div class="text-center">
                        <a class="small" href="{% url "users:login" %}">Volver</a>
                      </div>
                    </div>
                  </div>
                </div>

              </div>

            </div>

          </div>

        </div>
    </div>

{% endblock %}